version: '4.2'

services:
    products-db:
        image: postgres:17.0
        container_name: products-db
        volumes:
            - ~/storage_block/eda/products-db/data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: products
            POSTGRES_USER: esteban
            POSTGRES_PASSWORD: secret
        networks:
            - events-network

networks:
    events-network:
        external: true